/* Generated By:JavaCC: Do not edit this line. ScheduleParserConstants.java */
package tju.MSchedule.moudles;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScheduleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int LBRAC = 7;
  /** RegularExpression Id. */
  int RBRAC = 8;
  /** RegularExpression Id. */
  int LPARAN = 9;
  /** RegularExpression Id. */
  int RPARAN = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int NAME = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int LETTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"->\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"@\"",
    "\":\"",
    "<NAME>",
    "<DIGIT>",
    "<LETTER>",
  };

}
